package bg.tu_varna.sit.backend.models.enums.report.reportissue;

public enum Issue {
    EARTHQUAKE,
    TSUNAMI,
    LANDSLIDE,

    FIRE,
    FLOOD,
    RAIN,
    SNOW,
    AVALANCHE,
    HAIL,
    WIND,
    HURRICANE,
    SMERCH,
    FOG,
    STORM,
    THUNDERSTORM,
    LOW_TEMPERATURES,
    HIGH_TEMPERATURES,
    POLLUTED_AIR,

    NO_WATER_SUPPLY,
    NO_POWER_SUPPLY,
    NO_COMMUNICATIONS,
    EPIDEMIC,
    NUCLEAR_ACCIDENT,
    RADIATION_LEAK,
    CHEMICAL_SPILL,
    BACTERIOLOGICAL_CONTAMINATION,
    PROTEST,
    EXPLOSION,

    CLOSED_ROAD,
    ROAD_ACCIDENT,
    DIFFICULT_ROAD_CONDITIONS,
    ROADWORKS,
    ICY_ROAD,

    INFANTRY_ATTACK,
    AIR_ATTACK,
    NAVAL_ATTACK,
    BOMB,
    CIVIL_WAR,
    HOSTAGE_CRISIS,
    COUP,
    ASSASSINATION,
    TERRORISM,

    METEORITE_IMPACT,
    METEOR_RAIN,
    SOLAR_STORMS
}
